# github workflow to run on semver tags

name: Build Artifact

env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # fetch entire history, including tags
          fetch-tags: true

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Build and upload artifact
        run: make build-artifact
        continue-on-error: false
